---
title: "FIRST_5_STEPS"
author: '520004915'
date: "2024-04-11"
output: html_document
---
```{r setup, include=FALSE}
library(caret)
library(cvTools)
library(dplyr)
library(e1071)
library(GEOquery)
library(ggplot2)
library(glmnet)
library(limma)
library(pheatmap)
library(randomForest)
library(stringr)
library(tidyverse)
rm(list = ls())
```
Loading in the datasets
```{r}
gse1 ='GSE36059'
gse2 ='GSE129166'
eSet1 <- getGEO('GSE36059')
eSet1 <- eSet1$GSE36059_series_matrix.txt.gz
eSet2 <- getGEO('GSE129166')
eSet2 <- eSet2$GSE129166_series_matrix.txt.gz
exp1 <- exprs(eSet1)
phe1 <- pData(phenoData(eSet1))
feature1 <- fData(eSet1)
exp2 <- exprs(eSet2)
phe2 <- pData(phenoData(eSet2))
feature2 <- fData(eSet2)
```
Cleaning and merging of the datasets
```{r}
set.seed(3888)
#clean features
f1 <-feature1 %>% filter(`Gene Symbol` != '', !is.na(`Gene Symbol`))
f1$'Gene Symbol' <- sapply(strsplit(f1$'Gene Symbol', ' /// '), function(x) x[1])
f1$'Gene Symbol' <- make.unique(f1$'Gene Symbol', sep = '_')
f2 <-feature2 %>% filter(`Gene Symbol` != '', !is.na(`Gene Symbol`))
f2$'Gene Symbol' <- sapply(strsplit(f2$'Gene Symbol', ' /// '), function(x) x[1])
f2$'Gene Symbol' <- make.unique(f2$'Gene Symbol', sep = '_')
## Rename probe IDs in expression matrix to gene symbols
exp1 <- as.data.frame(exp1)
# Probe ID in column 1, gene symbol in column 11
gene_symbols1 <- f1[, c(1, 11)]
exp1[, 'ID'] <- rownames(exp1)
exp1 <- merge(x = exp1, y = gene_symbols1, by.x = 'ID')
f1 <- f1 %>% filter(`ID` %in% exp1$`ID`)
exp1[, 'Gene Symbol'] <- make.unique(exp1[, 'Gene Symbol'], sep = '_')
# Set gene symbols as the rownames of the data frame
rownames(exp1) <- exp1[, 'Gene Symbol']
exp1[, c('ID', 'Gene Symbol')] <- NULL
exp1 <- as.matrix(exp1)
exp2 <- as.data.frame(exp2)
gene_symbols2 <- f2[, c(1, 11)]
exp2[, 'ID'] <- rownames(exp2)
exp2 <- merge(x = exp2, y = gene_symbols2, by.x = 'ID')
f2 <- f2 %>% filter(`ID` %in% exp2$`ID`)
exp2[, 'Gene Symbol'] <- make.unique(exp2[, 'Gene Symbol'], sep = '_')
rownames(exp2) <- exp2[, 'Gene Symbol']
exp2[, c('ID', 'Gene Symbol')] <- NULL
exp2 <- as.matrix(exp2)
#conbime gene expressions
table(rownames(exp1) %in% rownames(exp2))
exp1 <- exp1[intersect(rownames(exp1),rownames(exp2)),]
exp2 <- exp2[intersect(rownames(exp1),rownames(exp2)),]
if(!identical(rownames(phe1),colnames(exp1))) exp1 = exp1[,match(rownames(phe1),colnames(exp1))]
if(!identical(rownames(phe2),colnames(exp2))) exp2 = exp2[,match(rownames(phe2),colnames(exp2))]
exp <- cbind(exp1,exp2)
#remove batch effects
batch_info <- c(rep(1, ncol(exp1)), rep(2, ncol(exp2)))
exprSet_corrected <- removeBatchEffect(exp, batch_info)
##set groups
phe1$outcome <- ifelse(str_detect(phe1$title, 'non-rejecting'), 'non-rejection',
                       ifelse(str_detect(phe1$title, 'ABMR'), 'ABMR',
                              ifelse(str_detect(phe1$title, 'TCMR'), 'TCMR', 'Other')))
phe1 <- phe1%>% filter(outcome != 'Other')#remove other
phe2 <-phe2 %>% mutate(
  ABMR_Status = ifelse(`abmr (no:ch1` == '0_Yes:1): 1', 'ABMR', 'ABMR Stable'),
  TCMR_Status = ifelse(`tcmr (no:ch1` == '0_borderline:1_TCMR:2): 1', 'TCMR', 'TCMR Stable')
  )%>%
    filter(!(ABMR_Status == 'ABMR' & TCMR_Status == 'TCMR')) %>%
  mutate(
    outcome = case_when(
      ABMR_Status == 'ABMR Stable' & TCMR_Status == 'TCMR Stable' ~ 'non-rejection',
      ABMR_Status == 'ABMR Stable' ~ 'TCMR',
      TCMR_Status == 'TCMR Stable' ~ 'ABMR',
      TRUE ~ NA_character_
    )
  )
###remove both TCMR and ABMR, then if the original sting was TCMR Stable, then it appears to be ABMR
## Remove corresponding columns of geo accession data from expression matrix that were dropped in pheno data
exprSet_corrected <- exprSet_corrected[, colnames(exprSet_corrected) %in% c(phe1$geo_accession, phe2$geo_accession)]
group <- table(c(phe1$outcome, phe2$outcome))
#normalisation
combine_symbol <- union(f1$`Gene Symbol`, f2$`Gene Symbol`)
eMat <- exprSet_corrected[rownames(exprSet_corrected) %in% combine_symbol, ]
gene_means <- rowMeans(eMat)
gene_percentile <- rank(gene_means) / length(gene_means)
threshold <- 0.25
filtered_genes <- eMat[gene_percentile > threshold,]
## [normalisation]
exprSet <- normalizeBetweenArrays(filtered_genes)
qx <- as.numeric(quantile(exprSet,c(0.,0.25,0.5,0.75,0.99,1.0),na.rm=T))
logC <- (qx[5]>100) ||
           (qx[6]-qx[1]>50 && qx[2]>0) ||
            (qx[2]>0 && qx[2]<1 && qx[4]>1 && qx[4]<2)
if (logC){
  exprSet [which(exprSet <=0)] <- NaN
  exprSet_clean <- log2(exprSet)
  print('log2 transformation finished')
}else{
  print('does not need log2 transformation')
}
#normalisaton done, see how it looks
boxplot(exp)#after combination
boxplot(exprSet_corrected)#bacth effected
boxplot(exprSet)#normaled
```
Exploring the dataset with PCA
```{r}
set.seed(3888)
gse_pca <- prcomp(t(exprSet))
df_toplot <- data.frame(c(phe1$outcome, phe2$outcome),
                        pc1 = gse_pca$x[,1], pc2 = gse_pca$x[,2])
ggplot(df_toplot, aes(x = pc1, y = pc2, color = c(phe1$outcome, phe2$outcome))) + 
  geom_point(size = 1.5) + labs(colour = "Outcome") +
  theme_minimal()
```

Feature selection -limma
```{r}
set.seed(3888)
combined_outcome = c(phe1$outcome, phe2$outcome)
#trans_exprSet = t(exprSet)
#Data = data.frame(trans_exprSet) 
Data = data.frame(exprSet) 
design <- model.matrix(~ 0 +combined_outcome, data = Data)
fit <- lmFit(Data, design)
fit <- eBayes(fit)

library(DT)
tT <- topTable(fit, n = Inf) 
DT::datatable(round(tT[1:100, ], 2))

```

```{r}
## Code for MA plot
df<- topTable(fit, number=nrow(fit), genelist=rownames(Data))
ggplot(df, aes(x = AveExpr, y = combined_outcomeTCMR))+
    geom_point(aes(colour=-log10(P.Value)), alpha=1/3, size=1) +
    scale_colour_gradient(low="blue",high="red")+
    ylab("log2 fold change") + xlab("Average expression")

ggplot(df, aes(x = AveExpr, y = combined_outcomeABMR))+
    geom_point(aes(colour=-log10(P.Value)), alpha=1/3, size=1) +
    scale_colour_gradient(low="blue",high="red")+
    ylab("log2 fold change") + xlab("Average expression")

ggplot(df, aes(x = AveExpr, y = combined_outcomenon.rejection))+
    geom_point(aes(colour=-log10(P.Value)), alpha=1/3, size=1) +
    scale_colour_gradient(low="blue",high="red")+
    ylab("log2 fold change") + xlab("Average expression")
    
## Code to extract negative log p-value
p.value = -log10(df$P.Value)
```

```{r}
p <- ggplot(df, aes(combined_outcomenon.rejection,-log10(P.Value)))+
    geom_point(aes(colour=-log10(P.Value)), alpha=1/3, size=1) +
    scale_colour_gradient(low="blue",high="red")+
    xlab("log2 fold change") + ylab("-log10 p-value")
p
```

KNN
```{r}
largevar = apply(Data, 1, var)
ind = which(largevar > quantile(largevar, 0.9))

X = as.matrix(t(Data[ind,]))
y = combined_outcome

cvK = 5  # number of CV folds
cv_50acc5_knn = c()
cv_acc_knn = c()

n_sim = 25 ## number of repeats
for (i in 1:n_sim) {

  cvSets = cvTools::cvFolds(nrow(X), cvK)  # permute all the data, into 5 folds
  cv_acc_knn= c()
  
  for (j in 1:cvK) {
    test_id = cvSets$subsets[cvSets$which == j]
    X_test = X[test_id, ]
    X_train = X[-test_id, ]
    y_test = y[test_id]
    y_train = y[-test_id]
    
    ## KNN
    fit5 = class::knn(train = X_train, test = X_test, cl = y_train, k = 5)
    cv_acc_knn[j] = mean(fit5 == y_test)
    
  }
  cv_50acc5_knn <- append(cv_50acc5_knn, mean(cv_acc_knn))
} ## end for
```

```{r}
mean(cv_50acc5_knn)
```

